"""create adoption_application donation and volunteer_application tables

Revision ID: 03cdf4bc96d9
Revises: 2c795a1a1e0b
Create Date: 2026-10-09 22:12:38.523380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cdf4bc96d9'
down_revision = '2c795a1a1e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_applications',
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.ngo_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('volunteer_id')
    )
    with op.batch_alter_table('volunteer_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_applications_ngo_id'), ['ngo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_applications_user_id'), ['user_id'], unique=False)

    op.create_table('adoption_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.animal_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.ngo_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('application_id')
    )
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adoption_applications_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_applications_ngo_id'), ['ngo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adoption_applications_user_id'), ['user_id'], unique=False)

    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('donated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['rescue_cases.case_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('donation_id')
    )
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_donor_id'), ['donor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donations_donor_id'))
        batch_op.drop_index(batch_op.f('ix_donations_case_id'))

    op.drop_table('donations')
    with op.batch_alter_table('adoption_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adoption_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_adoption_applications_ngo_id'))
        batch_op.drop_index(batch_op.f('ix_adoption_applications_animal_id'))

    op.drop_table('adoption_applications')
    with op.batch_alter_table('volunteer_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_volunteer_applications_ngo_id'))

    op.drop_table('volunteer_applications')
    # ### end Alembic commands ###
