"""create ngo animal and rescue_case tables

Revision ID: 2c795a1a1e0b
Revises: fbbf2f4394f4
Create Date: 2026-10-09 21:51:53.793882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c795a1a1e0b'
down_revision = 'fbbf2f4394f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngos',
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ngo_id')
    )
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ngos_user_id'), ['user_id'], unique=True)

    op.create_table('animals',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('ngo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.ngo_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('animal_id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_ngo_id'), ['ngo_id'], unique=False)

    op.create_table('rescue_cases',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('assigned_ngo', sa.Integer(), nullable=True),
    sa.Column('animal_type', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_ngo'], ['ngos.ngo_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('case_id')
    )
    with op.batch_alter_table('rescue_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescue_cases_assigned_ngo'), ['assigned_ngo'], unique=False)
        batch_op.create_index(batch_op.f('ix_rescue_cases_reported_by'), ['reported_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rescue_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescue_cases_reported_by'))
        batch_op.drop_index(batch_op.f('ix_rescue_cases_assigned_ngo'))

    op.drop_table('rescue_cases')
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_ngo_id'))

    op.drop_table('animals')
    with op.batch_alter_table('ngos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ngos_user_id'))

    op.drop_table('ngos')
    # ### end Alembic commands ###
